/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/meals': typeof MealsRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/meals': typeof MealsRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/meals': typeof MealsRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/recipes': typeof RecipesRoute
  '/scan': typeof ScanRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/intro'
    | '/meals'
    | '/processing'
    | '/profile'
    | '/quiz'
    | '/recipes'
    | '/scan'
    | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/intro'
    | '/meals'
    | '/processing'
    | '/profile'
    | '/quiz'
    | '/recipes'
    | '/scan'
    | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/intro'
    | '/meals'
    | '/processing'
    | '/profile'
    | '/quiz'
    | '/recipes'
    | '/scan'
    | '/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IntroRoute: typeof IntroRoute
  MealsRoute: typeof MealsRoute
  ProcessingRoute: typeof ProcessingRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  RecipesRoute: typeof RecipesRoute
  ScanRoute: typeof ScanRoute
  ShoppingRoute: typeof ShoppingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IntroRoute: IntroRoute,
  MealsRoute: MealsRoute,
  ProcessingRoute: ProcessingRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  RecipesRoute: RecipesRoute,
  ScanRoute: ScanRoute,
  ShoppingRoute: ShoppingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
