/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as LocaleRouteImport } from './routes/locale'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated.shopping'
import { Route as AuthenticatedScansRouteImport } from './routes/_authenticated.scans'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated.scan'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated.recipes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedMealsRouteImport } from './routes/_authenticated.meals'
import { Route as AuthenticatedHydrationRouteImport } from './routes/_authenticated.hydration'
import { Route as AuthenticatedFocosRouteImport } from './routes/_authenticated.focos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated.checkout'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated.add'
import { Route as ApiPublicHotmartRouteImport } from './routes/api/public/hotmart'
import { Route as AuthenticatedFocosHistoryRouteImport } from './routes/_authenticated.focos.history'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/locale',
  path: '/locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScansRoute = AuthenticatedScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMealsRoute = AuthenticatedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHydrationRoute = AuthenticatedHydrationRouteImport.update({
  id: '/hydration',
  path: '/hydration',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFocosRoute = AuthenticatedFocosRouteImport.update({
  id: '/focos',
  path: '/focos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHotmartRoute = ApiPublicHotmartRouteImport.update({
  id: '/api/public/hotmart',
  path: '/api/public/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFocosHistoryRoute =
  AuthenticatedFocosHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedFocosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/locale': typeof LocaleRoute
  '/paywall': typeof PaywallRoute
  '/plan': typeof PlanRoute
  '/processing': typeof ProcessingRoute
  '/quiz': typeof QuizRoute
  '/add': typeof AuthenticatedAddRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/focos': typeof AuthenticatedFocosRouteWithChildren
  '/hydration': typeof AuthenticatedHydrationRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/scan': typeof AuthenticatedScanRoute
  '/scans': typeof AuthenticatedScansRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/focos/history': typeof AuthenticatedFocosHistoryRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/locale': typeof LocaleRoute
  '/paywall': typeof PaywallRoute
  '/plan': typeof PlanRoute
  '/processing': typeof ProcessingRoute
  '/quiz': typeof QuizRoute
  '/add': typeof AuthenticatedAddRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/focos': typeof AuthenticatedFocosRouteWithChildren
  '/hydration': typeof AuthenticatedHydrationRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/scan': typeof AuthenticatedScanRoute
  '/scans': typeof AuthenticatedScansRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/focos/history': typeof AuthenticatedFocosHistoryRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/locale': typeof LocaleRoute
  '/paywall': typeof PaywallRoute
  '/plan': typeof PlanRoute
  '/processing': typeof ProcessingRoute
  '/quiz': typeof QuizRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/focos': typeof AuthenticatedFocosRouteWithChildren
  '/_authenticated/hydration': typeof AuthenticatedHydrationRoute
  '/_authenticated/meals': typeof AuthenticatedMealsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/scans': typeof AuthenticatedScansRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
  '/_authenticated/focos/history': typeof AuthenticatedFocosHistoryRoute
  '/api/public/hotmart': typeof ApiPublicHotmartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/locale'
    | '/paywall'
    | '/plan'
    | '/processing'
    | '/quiz'
    | '/add'
    | '/checkout'
    | '/dashboard'
    | '/focos'
    | '/hydration'
    | '/meals'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/scans'
    | '/shopping'
    | '/focos/history'
    | '/api/public/hotmart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/locale'
    | '/paywall'
    | '/plan'
    | '/processing'
    | '/quiz'
    | '/add'
    | '/checkout'
    | '/dashboard'
    | '/focos'
    | '/hydration'
    | '/meals'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/scans'
    | '/shopping'
    | '/focos/history'
    | '/api/public/hotmart'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/locale'
    | '/paywall'
    | '/plan'
    | '/processing'
    | '/quiz'
    | '/_authenticated/add'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/focos'
    | '/_authenticated/hydration'
    | '/_authenticated/meals'
    | '/_authenticated/profile'
    | '/_authenticated/recipes'
    | '/_authenticated/scan'
    | '/_authenticated/scans'
    | '/_authenticated/shopping'
    | '/_authenticated/focos/history'
    | '/api/public/hotmart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LocaleRoute: typeof LocaleRoute
  PaywallRoute: typeof PaywallRoute
  PlanRoute: typeof PlanRoute
  ProcessingRoute: typeof ProcessingRoute
  QuizRoute: typeof QuizRoute
  ApiPublicHotmartRoute: typeof ApiPublicHotmartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locale': {
      id: '/locale'
      path: '/locale'
      fullPath: '/locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scans': {
      id: '/_authenticated/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedScansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meals': {
      id: '/_authenticated/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hydration': {
      id: '/_authenticated/hydration'
      path: '/hydration'
      fullPath: '/hydration'
      preLoaderRoute: typeof AuthenticatedHydrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/focos': {
      id: '/_authenticated/focos'
      path: '/focos'
      fullPath: '/focos'
      preLoaderRoute: typeof AuthenticatedFocosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hotmart': {
      id: '/api/public/hotmart'
      path: '/api/public/hotmart'
      fullPath: '/api/public/hotmart'
      preLoaderRoute: typeof ApiPublicHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/focos/history': {
      id: '/_authenticated/focos/history'
      path: '/history'
      fullPath: '/focos/history'
      preLoaderRoute: typeof AuthenticatedFocosHistoryRouteImport
      parentRoute: typeof AuthenticatedFocosRoute
    }
  }
}

interface AuthenticatedFocosRouteChildren {
  AuthenticatedFocosHistoryRoute: typeof AuthenticatedFocosHistoryRoute
}

const AuthenticatedFocosRouteChildren: AuthenticatedFocosRouteChildren = {
  AuthenticatedFocosHistoryRoute: AuthenticatedFocosHistoryRoute,
}

const AuthenticatedFocosRouteWithChildren =
  AuthenticatedFocosRoute._addFileChildren(AuthenticatedFocosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFocosRoute: typeof AuthenticatedFocosRouteWithChildren
  AuthenticatedHydrationRoute: typeof AuthenticatedHydrationRoute
  AuthenticatedMealsRoute: typeof AuthenticatedMealsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedScansRoute: typeof AuthenticatedScansRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFocosRoute: AuthenticatedFocosRouteWithChildren,
  AuthenticatedHydrationRoute: AuthenticatedHydrationRoute,
  AuthenticatedMealsRoute: AuthenticatedMealsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedScansRoute: AuthenticatedScansRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LocaleRoute: LocaleRoute,
  PaywallRoute: PaywallRoute,
  PlanRoute: PlanRoute,
  ProcessingRoute: ProcessingRoute,
  QuizRoute: QuizRoute,
  ApiPublicHotmartRoute: ApiPublicHotmartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
